repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-merge-conflict
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
        exclude: ^frontend/src/data\.json$
      - id: trailing-whitespace
        files: ^(?!.*\.md$).*

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.9
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: gitleaks
        name: Detect hardcoded secrets
        entry: gitleaks git --pre-commit --redact --staged --verbose
        language: system
        pass_filenames: false
